dist: trusty
sudo: required
language: node_js
node_js:
- '12'
branches:
  only:
  - master

before_script:
- npm install -g @angular/cli
script:
- npm install
- npm run build

deploy:
  provider: heroku
  app: decide-angular
  strategy: git
  api_key:
    secure: cd6a03fc-fe90-484b-bbad-1b62ac88dd35
