#############
### build ###
#############

# base image
FROM node:14.17.0 as build

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@12.0.2

# add app
COPY . /app

# define environment configuration
ARG configuration=testing

# generate build
RUN ng build --output-path=dist --configuration=$configuration

############
### prod ###
############

# base image
FROM nginx:1.16.0-alpine

# copy artifact build from the 'build environment'
COPY --from=build /app/dist /usr/share/nginx/html

# expose port 80
EXPOSE 80

# add ngnix conf for angular url route paths
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# run nginx
CMD ["nginx", "-g", "daemon off;"]
